### ISSUE TITLE
EPIC: Define OPEN API spec for backend api service 🎯

### ISSUE THREAD

**Issue by lululeon** [colabco/cbld-api#2]
This epic will iteratively define the Open API spec that will help define a standard interface / api contract between the backend API and frontend & other consuming services.
⚠ This ticket is related to #1 

Refs:
- [reference docs](https://spec.openapis.org/oas/v3.1.0#:~:text=The%20OpenAPI%20Specification%20(OAS)%20defines%20a%20standard%2C%20language%2D,or%20through%20network%20traffic%20inspection).
- Tools for authoring api specs
  - https://apidog.com/
  - https://editor.swagger.io/ or https://editor-next.swagger.io/ (newer)

## API Contract.
The initial contract with the frontend will be centered on routes needed to support the mock Projects page depicted below
![image](https://github.com/colabco/cbld-api/assets/6601801/61bfdae6-2b0f-4dcc-b1df-320143e4ee40)

Implementation of each route must include
- addition of the route(s) to the api yaml spec and related notes, documentation
- implementation of the route handler
- addition of tests for the route

### Child Tickets
Models and routes implemented for the following
- [ ] fetch project links: #9 
- [ ] fetch project tech stack info: #10 
- [ ] fetch industry roles for project
- [ ] fetch project tasks
